// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuo2CnEWzx02SOl1X9jQLBC7-_TUcvpkM',
    appId: '1:33340499789:web:bfff15b3799cb5c5293904',
    messagingSenderId: '33340499789',
    projectId: 'todo-app-e6853',
    authDomain: 'todo-app-e6853.firebaseapp.com',
    storageBucket: 'todo-app-e6853.appspot.com',
    measurementId: 'G-59W9CZWR9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBNXsHDkl3x9hXhLbXd66x8cBOjEz4z9Q',
    appId: '1:33340499789:android:4864001de411422d293904',
    messagingSenderId: '33340499789',
    projectId: 'todo-app-e6853',
    storageBucket: 'todo-app-e6853.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCopNZQQojajeBNkJuJVmn5nporifqjjTE',
    appId: '1:33340499789:ios:83f6787316840002293904',
    messagingSenderId: '33340499789',
    projectId: 'todo-app-e6853',
    storageBucket: 'todo-app-e6853.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCopNZQQojajeBNkJuJVmn5nporifqjjTE',
    appId: '1:33340499789:ios:83f6787316840002293904',
    messagingSenderId: '33340499789',
    projectId: 'todo-app-e6853',
    storageBucket: 'todo-app-e6853.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );
}
